spring:
  application:
    name: media-tracker-backend

server:
  port: 8080

# ---- API  ----
search:
  anime:
    enabled: true
  music:
    enabled: true
  game:
    enabled: true
  book:
    enabled: true
  manga:
    enabled: true

jikan:
  base-url: https://api.jikan.moe/v4

mangadex:
  base-url: https://api.mangadex.org

itunes:
  base-url: https://itunes.apple.com

rawg:
  base-url: https://rawg.io/api
  api-key: "${RAWG_API_KEY:ff51c125cfc14b7abce7c70740910d24}"

openlibrary:
  base-url: https://openlibrary.org