spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://localhost:27017
      database: mediatracker
  application:
    name: media-tracker-backend

server:
  port: 8080

# ---- App Config (Security) ----
app:
  jwt:
    # Dies ist ein Default-Key für die Entwicklung.
    # In Produktion sollte dieser Wert lang, zufällig und geheim sein!
    secret: "secret_key_fuer_das_development_das_muss_spaeter_geendert_werden_wenn_das_projekt_irgedwann_fertig_ist_zu_irged_einem_sicherer_key_davor_war_das_hier_hardcoded_in_JwtService"
    access-token-expiration-in-seconds: 900 # 15 Minuten
    refresh-token-expiration-in-seconds: 1209600 # 14 Tage

# ---- API Feature Toggles ----
search:
  anime:
    enabled: true
  music:
    enabled: true
  game:
    enabled: true
  book:
    enabled: true
  manga:
    enabled: true
  movie:
    enabled: true
  series:
    enabled: true

# ---- External API Configs ----
jikan:
  base-url: https://api.jikan.moe/v4

itunes:
  base-url: https://itunes.apple.com

rawg:
  base-url: https://rawg.io/api
  api-key: "${RAWG_API_KEY:ff51c125cfc14b7abce7c70740910d24}"

openlibrary:
  base-url: https://openlibrary.org

imdb:
  base-url: https://api.imdbapi.dev